[[redirects]]
  from = "https://apprentices.seesparkbox.com"
  to = "https://apprentices.sparkbox.com"
  status = 301
  force = true

[[redirects]]
  from = "/apply-dev.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/apply-fed.html"
  to = "/"
  status = 301
  force = true
